#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/jai
#    username: jai
#    password: jai26092001
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  security:
#    user:
#      name: admin
#      password: admin
